### ISSUE TITLE
Global css being applied throughout Studio

### ISSUE THREAD

**Issue by fabien** [BretCameron/sanity-plugin-order-documents#10]
Hi Bret,

I just noticed that since I installed your plugin, there are few buttons that behave differently - especially on hover. You can see it in the screenshots below. Apparently your styles are being applied globally, and thereby overriding the Studio defaults.

https://github.com/BretCameron/sanity-plugin-order-documents/blob/c2974a004c60e32cf741558518e2aa790687d5c3/src/index.css#L26

![image](https://user-images.githubusercontent.com/2749/118393472-a5747600-b63f-11eb-9de3-18eaad785652.png)

![image](https://user-images.githubusercontent.com/2749/118393527-ec626b80-b63f-11eb-92fb-a855bc9b82d6.png)

**Comment by BretCameron** [comment]
Hi Fabien, good catch. I have renamed the classes so they are less generic and I am no longer targetting any HTML elements directly!

This improvement is available in 0.0.19.
