### ISSUE TITLE
Q: Possible to order by this field

### ISSUE THREAD

**Issue by j2is** [BretCameron/sanity-plugin-order-documents#11]
Hey I was wondering whether it was possible to order by the Manual Order field.

I have this in my document schema but it doesn't work for me:
```
export default {
  name: "product",
  title: "Product",
  type: "document",
  fields: [
    {
      name: "order",
      title: "Order",
      type: "number",
      description: "Set to 0 to order to top",
      hidden: false,
    },
  ],
  orderings: [
    {
      title: "Manual Order",
      name: "manualOrder",
      by: [{ field: "order", direction: "asc" }],
    }
  ]
};
```

**Comment by BretCameron** [comment]
Hi j2is, on my test site, I copied your `orderings` array and this worked as expected:

<img width="1665" alt="Screenshot 2021-05-21 at 14 18 57" src="https://user-images.githubusercontent.com/44526664/119143595-acd0c080-ba3f-11eb-8551-df948e687010.png">

<img width="1666" alt="Screenshot 2021-05-21 at 14 19 10" src="https://user-images.githubusercontent.com/44526664/119143601-ae9a8400-ba3f-11eb-8421-6f48d77babda.png">

This makes me think the error might be specific to your project, so I'll close this issue for now. However, if you can find any evidence that it might be an issue with the plugin, I'm happy to re-open the issue and take another look.

One way to check would be to see if running GROQ queries against the order property is working correctly, e.g.

```GROQ
*[_type == "movie"] | order(order asc)
```

Also, thank you for drawing my attention to the `orderings` feature. I wasn't aware of it, and it could be a good addition to the plugin's README!

**Comment by j2is** [comment]
Thanks Bret! It's odd as say I sort by anything else (title) for example it orders straight away. When I sort by manual order I have to scroll the documents until it loads a new set and then scroll back up only then does it order by manual order
