### ISSUE TITLE
dynamic order attributes

### ISSUE THREAD

**Issue by joecritch** [BretCameron/sanity-plugin-order-documents#2]
Hey! I just started using Sanity.io yesterday for my portfolio site, and immediately felt the need for this. (Came via https://github.com/sanity-io/sanity/issues/732) Great job. Followed instructions and works flawlessly.

One thing that would be cool is if the `order` field was dynamic and part of the UI. So you could create multiple sets of orders for the same document type? (Maybe this is going out of scope, but it was my first idea that came to mind.)

**Comment by BretCameron** [comment]
Thank you for the positive feedback! I think it's a great suggestion - and one which might give this plugin a continued purpose if/when Sanity decide to allow custom orders natively. 

To keep the plugin as simple as possible, we may prefer to put this functionality in a Settings / "Advanced Options" area. I'll make some headway on this when I have time, but would also welcome any contributions!

**Comment by BretCameron** [comment]
My suggestion is that - if you have the "order" field and at least one other hidden number field - you can see an additional dropdown in the top right corner:

<img width="600" alt="Screenshot 2020-10-16 at 16 06 01" src="https://user-images.githubusercontent.com/44526664/96275326-80e0ee80-0fc9-11eb-8416-60aedded316a.png">

**Comment by BretCameron** [comment]
Thank you! 

Support for this feature has been added in v0.0.5. Check out the "Custom Fields" section of README.md for details.

<img width="600" alt="Screenshot 2020-10-17 at 18 14 23" src="https://user-images.githubusercontent.com/44526664/96348998-a42c9c00-10a4-11eb-8c8f-72add7435dd1.png">
