### ISSUE TITLE
Move new pages on top when it's created

### ISSUE THREAD

**Issue by danil-vladimirov** [BretCameron/sanity-plugin-order-documents#6]
Hi, I got an issue. I successfully added the plugin and created the sorting of my pages. However, when I create a new page, it goes to the bottom of the sorted list and the bottom of everything on my page as well, while I want to have new things appear on the top.

Is there a way to configure the behaviour of sorting newly added things?

**Comment by BretCameron** [comment]
Would a better default be for the new page to appear at the top of the sorting list? Or perhaps an option to switch between "new items go to the top" and "new items go to the bottom"?

We're not yet storing any user configuration data, though this should be possible using `"part:@sanity/base/client"` (e.g. [sanity-plugin-mux](https://github.com/sanity-io/sanity-plugin-mux-input/blob/b923f858094150a2ec7f66dcb344c6a93adc3965/src/actions/secrets.js#L27)).

**Comment by BretCameron** [comment]
@danil-vladimirov as of version 0.0.14, the default behaviour of new items is to go to the top of the list.
