### ISSUE TITLE
Can't sort with the GraphQL-query given in the docs

### ISSUE THREAD

**Issue by olestole** [BretCameron/sanity-plugin-order-documents#7]
The docs prompts you to order the documents with the given:
`(sort: [{order: DESC}])`

It didn't work for me. I had to add the following to allow for sorting.
`(sort: {fields: order, order: DESC})`

**Comment by BretCameron** [comment]
It seems you might not be using the Sanity GraphQL API.

For example, the Gatsby GraphQL API has a sorting pattern that looks like your example: `sort: { fields: [frontmatter___date, frontmatter___title], order: [ASC, DESC] }`.

You can find out more about that [here](https://www.gatsbyjs.com/docs/graphql-reference/#sort).

To help people in your situation, I have added some additional copy to the README. 

### Using the query string from the README (Sanity GraphQL API - Gen 3)

Using the Sanity GraphQL API, the query string in the README produces this result:

<img width="1680" alt="Screenshot 2021-04-11 at 14 38 10" src="https://user-images.githubusercontent.com/44526664/114306355-ae6ba800-9ad3-11eb-9077-d14959700651.png">

### Using an incorrect query string

However, your query string throws an error: 

<img width="1680" alt="Screenshot 2021-04-11 at 14 38 49" src="https://user-images.githubusercontent.com/44526664/114306411-dc50ec80-9ad3-11eb-94ee-3643cf651440.png">
